server:
  port: 17002
  session:
    #单位是秒
    timeout: 10
spring:
  http:
    encoding:
      force: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    hikari:
      pool-name: spring-security/dsDev
      connection-timeout: 45000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 0
      connection-test-query: "select 1"
      validation-timeout: 1000
      isolate-internal-queries: true
  session:
    store-type: redis
security:
  basic:
    enabled: false

mydemo:
  security:
    browser:
      #loginPage: /demo-signIn.html
      loginTypeEnum: JSON
      signOutUrl: /demo-logout.html
    code:
      image:
        length: 4
        width: 67
        height: 23
        #可以配置哪些路径需要验证码
        url: /user
    social:
      qq:
        app-id: 100550231
        app-secret:
        providerId: callback.do
      filterProcessesUrl: /qqLogin
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4


